<?php namespace JF;
/**

Copyright 2018 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-077e25
Date:    2018-04-24 13:05:43
Version: v2.1.1
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-077e25",
    "email": {
        "to": "noloshacusub@noloshacusub.net",
        "cc": "",
        "bcc": "",
        "subject": "IKIJK Quiz",
        "template": "",
        "sendmail_from": "jquery.form@aol.com"
    },
    "admin": {
        "users": "admin:735e0",
        "dataDelivery": "emailAndFile",
        "save2dbExample": true
    },
    "thankyou": {
        "url": "",
        "message": "Jawaabtaada waa la helay!\n\nWaad ku mahadsan tahay farriintaada.  Degdeg waxaannu ku soo jawaabi doonaa.",
        "seconds": "10"
    },
    "autoResponse": {
        "includeAttachments": true,
        "subject": "",
        "template": ""
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "local",
    "smtp": {
        "host": "smtp.aol.com",
        "user": "jquery.form@aol.com",
        "password": "MailerTest2016",
        "port": "587",
        "security": "tls"
    },
    "mailgun": {
        "domain": "mg.jquery-form.com",
        "apiKey": "key-1fee8dabcdf62e1b78ef1c57bf553d6d",
        "fromEmail": "mailgun@jquery-form.com",
        "fromName": "JQuery Form"
    },
    "styles": {
        "iCheck": {
            "enabled": false,
            "skin": "flat",
            "colorScheme": "black"
        },
        "Select2": {
            "enabled": false
        }
    },
    "logics": [

    ],
    "fields": [
        {
            "label": "1. Ilaah wuxuu joogaa",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Qorraxda, dayaxa iyo xiddigaha.",
                        "checked": false
                    },
                    {
                        "label": "Kalluunka, shimbirraha iyo haadda.",
                        "checked": false
                    },
                    {
                        "label": "Nin.",
                        "checked": false
                    }
                ],
                "presetJson": "",
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Raalli ahow walaal, laakiin su'aashan lama dhammaystirin."
                    }
                }
            },
            "id": "f5",
            "cid": "c17"
        },
        {
            "label": "2. Maalintii afraad ee uumista Ilaah wuxuu abuuray",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Qorraxda, dayaxa iyo xiddigaha.",
                        "checked": false
                    },
                    {
                        "label": "Kalluunka, shimbirraha iyo haadda.",
                        "checked": false
                    },
                    {
                        "label": "Nin.",
                        "checked": false
                    }
                ],
                "presetJson": "",
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Raalli ahow walaal, laakiin su'aashan lama dhammaystirin."
                    }
                }
            },
            "id": "f7",
            "cid": "c28"
        },
        {
            "label": "3. Ilaah wuxuu rabaa",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "In isaga ragga keliyuhu jeclaado.",
                        "checked": false
                    },
                    {
                        "label": "In isaga dumarka keliyuhu jeclaado.",
                        "checked": false
                    },
                    {
                        "label": "In isaga ragga iyo dumarka, iyo carruurtuba ay wada jeclaadaan.",
                        "checked": false
                    }
                ],
                "presetJson": "",
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Raalli ahow walaal, laakiin su'aashan lama dhammaystirin."
                    }
                }
            },
            "id": "f8",
            "cid": "c34"
        },
        {
            "label": "4. Maalintii ugu dambaysay uumista, Ilaah",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Wuxuu kala soocay birriga iyo badaha.",
                        "checked": false
                    },
                    {
                        "label": "Wuxuu uumay nin.",
                        "checked": false
                    },
                    {
                        "label": "Wuxuu yiri, \"Iftiin ha ahaado\"",
                        "checked": false
                    }
                ],
                "presetJson": "",
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Raalli ahow walaal, laakiin su'aashan lama dhammaystirin."
                    }
                }
            },
            "id": "f9",
            "cid": "c39"
        },
        {
            "label": "5. Ilaah wuxuu jecel yahay",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Dembigeenna.",
                        "checked": false
                    },
                    {
                        "label": "Innaga iyo dembigeennaba.",
                        "checked": false
                    },
                    {
                        "label": "Innaga.",
                        "checked": false
                    }
                ],
                "presetJson": "",
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Raalli ahow walaal, laakiin su'aashan lama dhammaystirin."
                    }
                }
            },
            "id": "f10",
            "cid": "c44"
        },
        {
            "label": "6. Ilaah waa qoduus, taas aawadeed muxuu ciqaabi doonaa?",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Raalli ahow walaal, laakiin su'aashan lama dhammaystirin."
                    }
                }
            },
            "id": "f15",
            "cid": "c53"
        },
        {
            "label": "7. Bilowgii Ilaah muxuu abuuray? ",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Raalli ahow walaal, laakiin su'aashan lama dhammaystirin."
                    }
                }
            },
            "id": "f16",
            "cid": "c58"
        },
        {
            "label": "8. Bal yaa weligiis jiray, weligiisna jiri doona?",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Raalli ahow walaal, laakiin su'aashan lama dhammaystirin."
                    }
                }
            },
            "cid": "c63",
            "id": "f17"
        },
        {
            "label": "9. Waxaa jira Ilaah keliya oo run ah.",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Run",
                        "checked": false
                    },
                    {
                        "label": "Been",
                        "checked": false
                    }
                ],
                "presetJson": "",
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Raalli ahow walaal, laakiin su'aashan lama dhammaystirin."
                    }
                }
            },
            "cid": "c80",
            "id": "f20"
        },
        {
            "label": "10. Ilaah wax kasta wuu og yahay.",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Run",
                        "checked": false
                    },
                    {
                        "label": "Been",
                        "checked": false
                    }
                ],
                "presetJson": "",
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Raalli ahow walaal, laakiin su'aashan lama dhammaystirin."
                    }
                }
            },
            "id": "f19",
            "cid": "c75"
        },
        {
            "label": "Magacaaga oo dhan:",
            "field_type": "name",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "sender": "fullname",
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Fadlan magacaa u qor."
                    }
                }
            },
            "id": "f21",
            "cid": "c89"
        },
        {
            "label": "Cinwaanka Iimaylka:",
            "field_type": "email",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "sender": true,
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true,
                        "msg": "Fadlan cinwaankaaga iimaylka u qor."
                    }
                }
            },
            "id": "f22",
            "cid": "c94"
        },
        {
            "label": "Magaalada:",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ]
            },
            "id": "f23",
            "cid": "c99"
        },
        {
            "label": "Waddanka:",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ]
            },
            "cid": "c104",
            "id": "f24"
        },
        {
            "label": "Su'aal ama Ra'yi:",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small"
            },
            "id": "f25",
            "cid": "c111"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "Riix oo dir",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ],
    "licenseKey": ""
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class